### ISSUE TITLE
Info required about lockdown.yml

### ISSUE THREAD

**Issue by pavananms** [bbatsche/Ansible-PostgreSQL-Manage-Role#1]
Hi,
What is the use of Disable Login for postgres User.
After the above task we get "unable to connect to database: FATAL:  role \"postgres\" is not permitted to log in" error whenever trying to access the database using postgres user since the login is disabled for the same.

Even the task "Add Adminpack" fails with the same error.
Any reason for disabling the login and what are the alternatives for these.

**Comment by bbatsche** [comment]
Hi @pavananms,

First, I think you meant to create this issue on my [PostgreSQL-Install](/bbatsche/Ansible-PostgreSQL-Install-Role) repository, as that is where the `lockdown.yml` file exists.

To answer why it disables the `postgres` user, it's more for consistency with my other roles than anything else. I have similar roles for managing both MySQL and MongoDB and to make working with all three simple they all handle creating a database super user similarly. They disable or remove the server's default super user, if one exists (`postgres` for PostgreSQL, `root` for MySQL) and creates a new `db_admin` user that is authenticated by the database server (rather than the OS). This is also done for security reasons; best to not create multiple super users when they aren't (hypothetically) needed.

Finally, regarding the failure of adding the Adminpack, I'm guessing it's because you are using these roles on a server where PostgreSQL is already installed and configured. These roles are geared more for a "blank slate" where they can install and manage the Database from the beginning.

That said, one potential fix might be to make sure all the required packages are installed _before_ running any of these roles. `PosgreSQL-Install` will only trigger the `lockdown.yml` file if any of the three following packages are installed by it:
- `postgresql-{{ postgres_version }}`
- `postgresql-contrib-{{ postgres_version }}`
- `python-psycopg2`

If you make sure those packages are installed (for the correct version of postgres, `9.3` by default), then nothing will change in the install step, `lockdown.yml` won't be included, and the `postgres` user won't be modified in any way.
